### PR TITLE
Add Twitch API rate limit error

### PR DESCRIPTION
**Pull request by AntonioMIN**
This is for handling rate limit error.

https://dev.twitch.tv/docs/api/guide#twitch-rate-limits

### Usage Example
``` ts
const twitchApi = new TwitchApi({
  // ...
  wait_ratelimit_reset: false // Default: true
});

try {
  const streams = await twitch.getStreams();
  // ...
} catch (e) {
  if (e instanceof TwitchApiRateLimitError) {
    // Handle rate limit
    await sleep(e.ratelimit.reset * 1000 - Date.now());
  }
}
```

### CODE REVIEW

**Comment by AntonioMIN** [comment]
@Plazide I added about rate limit error to handle it. Please let me know if I'm missing something :)

**Comment by Plazide** [comment]
Hey, nice work!

Although, I feel like we should handle the rate limit error silently, like we are doing with the refresh token. We could instead emit an event when the rate limit error occurs to inform the consumer of that a rate limit has been hit.

So, where you are checking the response status for 429, you should instead await the rate limit reset, then emit an event containing the rate limit info, and finally retry the request.

I want to hide as much complexity as possible from the consumer to keep it simple. Does that make sense?

**Comment by AntonioMIN** [comment]
@Plazide I reflected your opinion. And i add `wait_ratelimit_reset` option for who want to handle rate limit error.

**Review by Plazide — CHANGES_REQUESTED** [review]
I think it's a good idea to have the option to handle the rate limit error yourself, but I think the default should be automatic handling of the rate limit. That way, we keep it simple for the consumer and can expose the error for more advanced consumers.

So maybe change the `wait_ratelimit_reset` option to something like `expose_ratelimit_errors` and change the condition to reflect this.

**Review by Plazide — APPROVED** [review]
Looks good. Nice work!

I'll merge this and will make a new release to NPM soon.

**Comment by AntonioMIN** [comment]
@Plazide Could you release new version to NPM? I need this feature :)

**Comment by Plazide** [comment]
Just released this with version 0.5.0.

Sorry for the delay.

**Pull request merged**
